name: Build

on:
  push:
    branches: ["*"]

jobs:
  build_windows:
    runs-on: ["windows-latest"]
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build something requiring CL.EXE
        run: |
          cl /Wall /link /out:unansi.exe
