name: Build

on:
  push:
    branch: ["*"]

jobs:
  build_windows:
    runs-on: ["windows-latest"]
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        run: "cl /Wall unansi.c /link /out:unansi.exe"

  build_linux:
    strategy:
      matrix:
        os: 
          - "ubuntu-latest"
          - "macos-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: "cc -Wall unansi.c -o unansi"
