name: Build

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  make-release:
    strategy:
      matrix:
        include:
          - os: "ubuntu-latest"
            asset_name: unansi-linux-amd64
            out: unansi
          - os: "macos-14"
            asset_name: unansi-macos-arm64
            out: unansi
          - os: "macos-13"
            asset_name: unansi-macos-amd64
            out: unansi
          - os: "windows-latest"
            asset_name: unansi-windows-amd64
            out: unansi.exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        if: runner.os == 'Windows'
        run: "cl /Wall /O2 unansi.c /link /out:${{ matrix.out }}"
      - name: Build
        if: runner.os == 'Linux'
        run: |
          gcc -Wall -O3 -fprofile-generate unansi.c -o ${{ matrix.out }}
          ./benchmark.sh
          gcc -Wall -O3 -fprofile-use unansi.c -o ${{ matrix.out }}
      - name: Build
        if: runner.os == 'MacOS'
        run: |
          clang -Wall -O3 -fprofile-generate unansi.c -o ${{ matrix.out }}
          ./benchmark.sh
          llvm-profdata merge -output=default.profdata *.profraw
          clang -Wall -O3 -fprofile-use unansi.c -o ${{ matrix.out }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.out }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
